-- Aprovações: trilha de decisão + envio direto pelo sistema
alter table public.aprovacoes_pendentes
  add column if not exists resumo_final text,
  add column if not exists resposta_manual text,
  add column if not exists motivo_recusa text,
  add column if not exists decidido_por uuid references auth.users (id),
  add column if not exists decidido_em timestamptz,
  add column if not exists enviado_whatsapp boolean not null default false,
  add column if not exists mensagem_id text;

comment on column public.aprovacoes_pendentes.resumo_final is
  'Texto efetivamente enviado ao cliente (resumo da IA, possivelmente editado pelo advogado)';
comment on column public.aprovacoes_pendentes.resposta_manual is
  'Resposta escrita manualmente pelo advogado quando status = respondido_manual';
comment on column public.aprovacoes_pendentes.motivo_recusa is
  'Motivo registrado pelo advogado quando status = recusado';
comment on column public.aprovacoes_pendentes.enviado_whatsapp is
  'true quando o próprio sistema enviou a mensagem ao cliente via EvoGo';

-- Prazos do escritório (exigência INSS, recurso, perícia, audiência, outro)
create table if not exists public.app_prazos (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  criado_por   uuid references auth.users (id),
  cpf          text,
  caso_id      bigint references public.casos_novos (id) on delete set null,
  processo_id  bigint references public.processos_clientes (id) on delete set null,
  titulo       text not null,
  tipo         text not null default 'outro',
  descricao    text,
  data_prazo   date not null,
  concluido    boolean not null default false,
  concluido_em timestamptz
);

create index if not exists app_prazos_data_idx on public.app_prazos (data_prazo) where not concluido;
create index if not exists app_prazos_cpf_idx on public.app_prazos (cpf);

alter table public.app_prazos enable row level security;

drop policy if exists "prazos_select" on public.app_prazos;
create policy "prazos_select" on public.app_prazos
  for select to authenticated using (true);

drop policy if exists "prazos_insert" on public.app_prazos;
create policy "prazos_insert" on public.app_prazos
  for insert to authenticated with check (true);

drop policy if exists "prazos_update" on public.app_prazos;
create policy "prazos_update" on public.app_prazos
  for update to authenticated using (true) with check (true);

drop policy if exists "prazos_delete" on public.app_prazos;
create policy "prazos_delete" on public.app_prazos
  for delete to authenticated using (true);

-- Realtime na fila de aprovações (badge/lista ao vivo)
do $$
begin
  alter publication supabase_realtime add table public.aprovacoes_pendentes;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.app_prazos;
exception when duplicate_object then null;
end $$;
